#Define function to error check contracts - TIER 3

##TIER 3 =
##WRITING AND RE-WRITING ERROR FILE BASED ON THE CONTRACTS DATAFRAME
##BASED ON RE-RUNNING TIERS 1 AND 3 TO HONE DOWN THE CLEANED AND ERROR CONTRACTS DATA